// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PF.Persistencia.Context;

namespace PF.Persistencia.Migrations
{
    [DbContext(typeof(FinalProjectContext))]
    [Migration("20190908155934_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("PF.Dominio.Model.Activity", b =>
                {
                    b.Property<int>("ActivityId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseId");

                    b.Property<int?>("ConstructionId");

                    b.Property<double>("Cost");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<int>("State");

                    b.HasKey("ActivityId");

                    b.HasIndex("ConstructionId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("PF.Dominio.Model.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseId");

                    b.Property<int>("FamilyId");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<int>("State");

                    b.HasKey("CategoryId");

                    b.HasIndex("FamilyId");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("PF.Dominio.Model.Construction", b =>
                {
                    b.Property<int>("ConstructionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseId");

                    b.Property<double>("Cost");

                    b.Property<DateTime>("EndDate");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Nombre");

                    b.Property<DateTime>("StartDate");

                    b.Property<int>("State");

                    b.HasKey("ConstructionId");

                    b.ToTable("Constructions");
                });

            modelBuilder.Entity("PF.Dominio.Model.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseId");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<int>("State");

                    b.HasKey("FamilyId");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("PF.Dominio.Model.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivityId");

                    b.Property<int>("BaseId");

                    b.Property<int?>("ItemId1");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("State");

                    b.HasKey("ItemId");

                    b.HasIndex("ActivityId");

                    b.HasIndex("ItemId1");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("PF.Dominio.Model.Material", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseId");

                    b.Property<int>("CategoryId");

                    b.Property<int?>("ItemId");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<int>("State");

                    b.Property<int>("Unity");

                    b.HasKey("MaterialId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ItemId");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("PF.Dominio.Model.Permission", b =>
                {
                    b.Property<int>("PermissionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseId");

                    b.Property<string>("Code");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<int>("State");

                    b.HasKey("PermissionId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("PF.Dominio.Model.Provider", b =>
                {
                    b.Property<int>("ProviderId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<int>("BaseId");

                    b.Property<ulong>("CUIT");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<int>("State");

                    b.HasKey("ProviderId");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("PF.Dominio.Model.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseId");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<int>("State");

                    b.HasKey("RolId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PF.Dominio.Model.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BaseId");

                    b.Property<string>("Mail");

                    b.Property<DateTime>("ModificationDate");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("State");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PF.Dominio.Model.Activity", b =>
                {
                    b.HasOne("PF.Dominio.Model.Construction")
                        .WithMany("Activities")
                        .HasForeignKey("ConstructionId");
                });

            modelBuilder.Entity("PF.Dominio.Model.Category", b =>
                {
                    b.HasOne("PF.Dominio.Model.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PF.Dominio.Model.Item", b =>
                {
                    b.HasOne("PF.Dominio.Model.Activity")
                        .WithMany("Items")
                        .HasForeignKey("ActivityId");

                    b.HasOne("PF.Dominio.Model.Item")
                        .WithMany("Items")
                        .HasForeignKey("ItemId1");
                });

            modelBuilder.Entity("PF.Dominio.Model.Material", b =>
                {
                    b.HasOne("PF.Dominio.Model.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PF.Dominio.Model.Item")
                        .WithMany("Materials")
                        .HasForeignKey("ItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
